# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Python base image
FROM python:3.12-slim-bookworm AS build

# Set the working directory
WORKDIR /app

# Copy the pyproject.toml and uv.lock to the working directory
COPY pyproject.toml uv.lock /app/

# Install hatchling and sync dependencies
RUN pip install hatchling && \
    uv sync --frozen --no-install-project --no-dev --no-editable

# Copy the source code
COPY src /app/src

# Build the package
RUN uv build

# Use a new base image for running
FROM python:3.12-slim-bookworm

# Set the working directory
WORKDIR /app

# Copy the built package from the build stage
COPY --from=build /app/dist /app/dist

# Install the package
RUN pip install /app/dist/*.whl

# Set the entry point to run the server
ENTRYPOINT ["mcp-discord-chat"]
